version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "CyberFlameGO"
    reviewers:
      - "CyberFlameGO"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    assignees:
      - "CyberFlameGO"
    reviewers:
      - "CyberFlameGO"
